drop table HOADON;
CREATE TABLE [dbo].[HOADON]
(
	[EMAIL] NVARCHAR(50) NOT NULL , 
    [MADONHANG] NVARCHAR(50) NOT NULL, 
    [TENSP] NVARCHAR(MAX) NULL, 
    [SOLUONG] NUMERIC NULL, 
    [DONGIA] NUMERIC NULL, 
    [TONGTIEN] NUMERIC NULL, 
    [TENKH] NVARCHAR(50) NULL, 
    [NGAYDAT] DATETIME NULL, 
    [TOTAL] NUMERIC NULL, 
    PRIMARY KEY ([EMAIL], [MADONHANG])
);
SELECT GETDATE()